In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

xl = pd.ExcelFile("./MergedData.xlsx")
xl.sheet_names 
[u'Data']
df = xl.parse("Data")
df.head(30)

     Id  Expertise1 Guided1  Outcome1  Expertise2 Guided2  Outcome2
0    C1           4       N       0.0         7.0       N       0.0
1    C2           3       N       3.0         7.0       N       0.0
2    E1           2       Y       1.0         6.0       Y       1.0
3    C3           3       N       4.0         7.0       N       0.0
4    C4           2       N       3.0         8.0       N       1.0
5    E2           3       Y       2.0         5.0       Y       0.0
6    E3           0       Y       2.0         4.0       Y       1.0
7    E4           4       Y       5.0         7.0       Y       2.0
8    E5           4       Y       0.0         4.0       Y       2.0
9    C5           3       N       0.0         7.0       N       0.0
10   C6           3       N       1.0         5.0       N       0.0
11   E6           3       Y       3.0         5.0       Y       0.0
12   E7           3       Y       3.0         6.0       Y       0.0
13   E8           1       Y       NaN         6.0       Y       0.0
14   C7           2       N       3.0         6.0       N       0.0
15   C8           1       N       4.0         6.0       N       0.0
16   E9           1       Y       0.0         5.0       Y       2.0
17   C9           3       N       4.0         5.0       N       0.0
18  E10           0       Y       3.0         5.0       Y       0.0
19  C10           0       N       3.0         6.0       N       0.0
20  E11           0       Y       1.0         9.0       Y       2.0
21  C11           3       N       4.0         6.0       N       0.0
22  C12           1       N       NaN         7.0       N       0.0
23  E12           3       Y       2.0         6.0       Y       2.0
24  C13           4       N       2.0         7.0       N       0.0
25  E13           0       Y       1.0         7.0       Y       1.0
26  C14           1       N       NaN         7.0       N       0.0
27  E14           0       Y       NaN         NaN       Y       NaN